server:
  port: 5001
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    username: root
    password: root
  kafka:
    listener:
      ack-mode: MANUAL_IMMIDIATE
    consumer:
      bootstarp-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apahe.kafka.common.serailization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
